return {}
-- return {
--   {
--     "CopilotC-Nvim/CopilotChat.nvim",
--     dependencies = {
--       { "github/copilot.vim" }, -- or zbirenbaum/copilot.lua
--       { "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
--     },
--     build = "make tiktoken", -- Only on MacOS or Linux
--     config = function()
--       local copilot = require("CopilotChat")
--
--       copilot.setup()
--
--       local keymap = vim.keymap
--
--       keymap.set("n", "<leader>cc", "<cmd>CopilotChatToggle<CR>", { desc = "Toggle Copilot chat" })
--       keymap.set("n", "<leader>cs", "<cmd>CopilotChatModel<CR>", { desc = "Select Copilot chat model" })
--       keymap.set("n", "<leader>ce", "<cmd>CopilotChatExplain<CR>", { desc = "Select Copilot chat model" })
--     end,
--   },
-- }
